"use client";

import React, { useEffect, useState } from "react";
import { Container, Typography, CircularProgress, Box } from "@mui/material";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { ArrowUp, ShieldCheck, Timer, DollarSign, Users } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from 'react-router-dom';

export default function PrivacyPolicy() {
  return (
    <div className="overflow-x-hidden">
      <ThemeProvider defaultTheme="dark">
        <div className="min-h-screen flex flex-col bg-white dark:bg-background text-foreground w-full">
          <Navbar />

          {/* 🔷 Hero Banner Section */}
          <section className="w-full bg-gradient-to-r from-black to-white py-28 px-4 text-center text-white animate-fade-in">
            <div className="max-w-5xl mx-auto pt-8">
              <h1 className="text-4xl md:text-5xl font-bold mb-3 animate-fade-in-up">Privacy Policy</h1>
              <p className="text-lg md:text-xl animate-fade-in-up delay-200">
                Your privacy matters. Learn how we collect, use, and protect your data.
              </p>
            </div>
          </section>

          {/* Adding animation styles */}
          <style>{`
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }

  @keyframes fade-in-up {
    0% {
      opacity: 0;
      transform: translateY(20px);
    }
    100% {
      opacity: 1;
      transform: translateY(0);
    }
  }

  .animate-fade-in {
    animation: fade-in 1.5s ease-in-out forwards;
  }

  .animate-fade-in-up {
    animation: fade-in-up 1s ease-in-out forwards;
  }

  .delay-200 {
    animation-delay: 200ms;
  }
`}</style>



          {/* 🔹 Main Content */}
          <main className="w-full py-12 px-6 md:px-10 lg:px-20 text-left">
            <div className="max-w-6xl mx-auto space-y-10 text-base leading-relaxed text-muted-foreground text-justify">


              <section>
                <h1 className="text-2xl font-semibold mb-2">Welcome to DOR</h1>
                <p>
                  Welcome to the DOR (Discount On Rent)! DOR is a platform where you can pay House/Office Rent and get rewards  as a “DOR Money” for shopping households’ items from Vendor.

                  This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

                  At RSoultek Consulting India Pvt. Ltd., (Worked under the brand of DOR), we are devoted to secure your personal information and letting you know about how we use the information. This privacy policy applies to all information accumulated, and all transaction upheld through the DOR app and services. This privacy policy describes the personal information we collect, how it’s utilized and shared, and your decisions with respect to this information. Each time you use the DOR platform or give us data, it is expected of course that you are accepting the practices and conditions depicted in this privacy policy.

                  Kindly read the privacy policy cautiously before using or registering on the platform or getting to any data or benefiting any services through the platform.              </p>
                <p className="mt-4">
                  This document is an electronic record in terms of the Information Technology Act, 2000... (continue full content here as in your original post)
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Information Shared with Us</h2>
                <p>
                  At the point when you start using the DOR Application, You have to give specific data to Us willfully while registering on the platform for profiting services including however not restricted to Your Name, contact number, email address, residential address, proof of identity such as Permanent Account Number (PAN) or any other document recognized by the Government for identification, provided through the Platform (“Personal Information”).

                  In accordance with the service consumed by you occasionally, we may expressly look for extra data including address, payment or banking data, credit/debit card details and some other legislative distinguishing proof numbers or documents. You might decide to give such information on the off chance that you wish to use the services provided by the Application. Occasionally, during your use of the DOR App, DOR might expect admittance to specific extra data, for example, SMS and Location. This includes transaction details related to your use of our services including the type of services you requested, the payment method, amount and other related transactional and financial information.              </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Disclosure of Data with Outsiders</h2>
                <p>
                  DOR will keep Your Personal data secret to the most extreme conceivable degree. DOR limits the exposure of Personal Data to DOR representatives, self employed entities, subsidiaries, experts, business partners, specialist co-ops and merchants of DOR Administration, on a restricted information, and provided that the divulgence will empower that substance to furnish DOR with business, expert, professional.

                  Third party services providers who provide services such as contact information verification, payment processing, order fulfillment, customer service, website hosting, data analysis, marketing assistance, infrastructure provision, IT services, auditing services and other similar services to enable them to provide the services;

                  DOR might show designated outsider online promotions on the DOR website/application. We may likewise promote our exercises and authoritative objectives on different websites/applications. We might team up with other site/application administrators as well as organization promoters to do as such. We demand you to peruse and see such concerned outsider security approaches to comprehend their works on connecting with promoting, including what kind of data they might gather about your web use. No personally recognizable data is imparted to any outsider online promoter or website or application as a feature of any such movement.              </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Safety and Security of Data</h2>
                <p>
                  Your DOR profile is fully protected with OTP verification to registered number, so just you and approved DOR representatives approach your account data. To keep up with this assurance, don’t give your OTP to anybody. DOR employees won’t ever proactively connect with you and request any private account information, including your OTP.  DOR bends over backward to guarantee that your data is secure on its platform. DOR has staff devoted to keeping up with privacy policy as presented in this and other security drives, occasionally surveying web security and ensuring that each DOR employees knows about our privacy policy. DOR explicitly disavows any obligation that might emerge should some other individual get the data you submit on the DOR platform. DOR has safety efforts set up to protect against the misfortune, abuse and modification of the data under our influence. Your data might be moved to and kept up with on system networks which might be situated beyond the state and country. We urge our user to know when they pass on the DOR platform to peruse the privacy explanations of each website that gathers actually recognizable data. This privacy policy applies exclusively to data gathered by the DOR platform.              </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Data Retention and Deletion</h2>
                <p>
                  DOR holds user information however long essential for its motivations. This implies that we hold various classes of information for various timeframes relying upon the classification of client to whom the information relates, the sort of information, and the reasons for which we gathered the information. Clients might demand cancellation of their account whenever through the component in the application or by sending a mail to DOR support as given in the App. DOR might hold client information after a deletion demand because of legal or administrative necessities or for the reasons expressed in this policy. Following a account erasure demand, DOR suspends the user account, and will hold the user information gathered till that mark of time.

                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Correction and Changes to Privacy Policy</h2>
                <p>
                  DOR reserves all authority to change this policy every once in a while. We urge user to occasionally review this policy for the most recent data. Any changes or updates will be effective immediately. We will keep on correcting the option to change our privacy policy and practices, and how we use the gathered information of our clients.

                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Cookies</h2>
                <p>
                  Like some other website, DOR also uses ‘cookies’. These cookies are used to store information including visitors’ preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users’ experience by customizing our web page content based on visitors’ browser type and/or other information.

                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Concerns</h2>
                <p>
                  If you have any concerns, or suggestions regarding our Privacy Policy, We can be reached using the contact information on our “Contact Us” page or at Support@dorpay.in

                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">* Grievance Officer</h2>
                <p>
                  If you have a complaint in regards to our Privacy Policy or information, you might contact our Grievance Officer at legal@dorpay.in.

                </p>
              </section>

              <p className="text-sm mt-10">
                Last updated: April 14, 2025
              </p>
            </div>


          </main>
          <footer className="bg-background py-12 px-6 md:px-12 border-t border-border">
            <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">
              <div className="md:col-span-2">
                <img src="/newlogo.png" alt="DORPay Logo" className="w-16 h-16" />

                {/* <h3 className="text-2xl font-semibold mb-4">
                  DORPay<span className="text-primary/80">.</span>
                </h3> */}
                <p className="text-muted-foreground max-w-md mb-6">
                  Discover the perfect property that matches your lifestyle and
                  preferences with our curated selection of premium DORPay.
                </p>
                <div className="flex space-x-4">
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Twitter
                  </a>
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Facebook
                  </a>
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Instagram
                  </a>
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    LinkedIn
                  </a>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-4">Explore</h4>
                <ul className="space-y-2">
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Properties
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Agents
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Locations
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Blog
                    </a>
                  </li>
                </ul>
              </div>

              <div>
                <h4 className="font-medium mb-4">Contact</h4>
                <ul className="space-y-2 text-muted-foreground">
                  <li>Rsoultek Consulting India Pvt Ltd,</li>
                  <li>
                    CoWrks, RMZ Ecoworld, Ground Floor Bay Area, 6A,
                    Devarabisanahalli,
                  </li>
                  <li>Bengaluru, Karnataka, India- 560103</li>
                  <li>
                    <a
                      href="mailto:support@dorpay.in"
                      className="hover:text-foreground transition-colors"
                    >
                      support@dorpay.in
                    </a>
                  </li>
                  <li>
                    <a
                      href="tel:+919844809969"
                      className="hover:text-foreground transition-colors"
                    >
                      +91 9844809969
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            <div className="max-w-7xl mx-auto mt-12 pt-6 border-t border-border text-center sm:text-left sm:flex sm:justify-between sm:items-center">
              <p className="text-muted-foreground text-sm">
                © {new Date().getFullYear()} DORPay. All rights reserved.
              </p>
              <div className="mt-4 sm:mt-0 flex justify-center sm:justify-end space-x-6 text-sm">
                <a
                  href="/privacy-policy"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  Privacy Policy
                </a>
                <a
                  href="/TermsConditions"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  Terms of Service
                </a>
                <a
                  href="#"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  Cookies Policy
                </a>
              </div>
            </div>
          </footer>
        </div>
      </ThemeProvider>
    </div>
  );
}
