"use client";

import React, { useEffect, useState } from "react";
import { Container, Typography, CircularProgress, Box } from "@mui/material";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { ArrowUp, ShieldCheck, Timer, DollarSign, Users } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from 'react-router-dom';

export default function TermsConditions() {
  return (
    <div className="overflow-x-hidden">
      <ThemeProvider defaultTheme="dark">
        <div className="min-h-screen flex flex-col bg-background text-foreground w-full">
          <Navbar />

          {/* 🔷 Hero Banner Section */}
          <section className="w-full bg-gradient-to-r from-black to-white py-28 px-4 text-center text-white animate-fade-in">
            <div className="max-w-5xl mx-auto mt-6">
              <h1 className="text-4xl md:text-5xl font-bold mb-3 animate-fade-in-up">Terms & Conditions</h1>
              <p className="text-lg md:text-xl animate-fade-in-up delay-200">
                Understand the rules and guidelines for using our services.
              </p>
            </div>
          </section>

          {/* Adding animation styles */}
          <style>{`
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }

  @keyframes fade-in-up {
    0% {
      opacity: 0;
      transform: translateY(20px);
    }
    100% {
      opacity: 1;
      transform: translateY(0);
    }
  }

  .animate-fade-in {
    animation: fade-in 1.5s ease-in-out forwards;
  }

  .animate-fade-in-up {
    animation: fade-in-up 1s ease-in-out forwards;
  }

  .delay-200 {
    animation-delay: 200ms;
  }
`}</style>


          {/* 🔹 Main Content */}
          <main className="w-full py-12 px-6 md:px-10 lg:px-20 text-left">
            <div className="max-w-6xl mx-auto space-y-10 text-base leading-relaxed text-muted-foreground text-justify">

              <section>
                <h1 className="text-2xl font-semibold mb-2">Welcome to DOR</h1>
                <p>
                  Welcome to the DOR (Discount On Rent)! DOR is a platform where you can pay House/Office Rent and get rewards  as a “DOR Money” for shopping households’ items from Vendor.

                  <br></br>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.             </p>
                <p className="mt-4">
                  <ul className="list-disc space-y-4 pl-6 text-muted-foreground text-sm">
                    <li>
                      These terms and conditions under this agreement (“User Terms”) apply
                      on the usage of our website <strong>www.dorpay.in</strong> (“Website“),
                      Service and to all information, recommendations and/or services
                      provided to you on or through the Website and/or through the Support at{' '}
                      <a href="mailto:support@dorpay.in" className="text-blue-500 underline">
                        support@dorpay.in
                      </a>.
                    </li>
                    <li>
                      The agreements referenced in this agreement alongside the Privacy
                      Policy comprise the whole agreement between the User and DOR concerning
                      admittance to and utilization of the site and the Services presented by
                      DOR, overriding any earlier composed or oral agreements comparable to a
                      similar topic thus.
                    </li>
                    <li>
                      These terms of purpose (“Terms”) administer Your utilization of the
                      Platform, and with the end goal of these Terms the Organization may any
                      place setting so require, be additionally alluded to as, “DOR”, “We”,
                      “Us”, or “Our” and the expressions “You”, “Your” or “User” allude to user
                      of the platform.
                    </li>
                    <li>
                      We esteem the trust You place in Us. That is the reason; We keep up with
                      sensible security norms for getting the Transactions and Your data.
                    </li>
                    <li>
                      Kindly read these Terms carefully before you utilize the Application. In
                      the event that you don’t consent to these Terms, You may not utilize the
                      services (characterized hereinafter) on the platform, and we request you
                      to uninstall the Application.
                    </li>
                    <li>
                      By even just utilizing/getting to the platform, You will contract with
                      DOR and You mean Your acknowledgment to these Terms and other DOR
                      policies (counting however not restricted to the cancelation and refund
                      policy of the Company and issued Privacy Policy) as posted on the
                      Platform and revised occasionally, which produces results on the date on
                      which You utilize the Platform, and consequently create a legally binding
                      agreement to keep something similar.
                    </li>
                    <li>
                      Further, by outfitting Your personal data, You agree to DOR getting to
                      Your own data to deliver the Services, You likewise concur that You are
                      keen on profiting the services through the platform as per these Terms.
                    </li>
                    <li>
                      <strong>RSOULTEK CONSULTING INDIA PVT. LTD.</strong> is a private company
                      registered under the Companies Act, 2013 having its registered office at
                      CoWrks, RMZ Ecoworld, Ground Floor Bay Area, 6A, Devarabisanahalli,
                      Bengaluru, Karnataka, India (hereinafter collectively referred to as
                      “DOR”).
                    </li>
                  </ul>              </p><br></br>
                <h2>DOR is a registered trademark of RSoultek Consulting India Private Limited.</h2>
              </section>
              <section>
                <h2 className="text-2xl font-semibold mb-2">Definitions:</h2>
                <p className="text-base leading-relaxed text-muted-foreground">
                  <ul className="list-disc space-y-4 pl-6 text-muted-foreground text-sm">
                    <li>
                      <strong>“Applicable Law”</strong> shall mean any statute, law, regulation, ordinance,
                      rule, judgment, order, decree, by-law, approval from the concerned authority, government
                      resolution, order, directive, guideline, policy, requirement, or other governmental
                      restriction or any similar form of decision of, or determination by, or any interpretation
                      or adjudication having the force of law of any of the foregoing, by any concerned authority
                      having jurisdiction over the matter in question.
                    </li>
                    <li>
                      <strong>“Service”</strong> shall mean technology platform provided by DOR that allows Merchants
                      to offer a differentiated, hassle-free buying experience to eligible Users, including a tab
                      offered by the Merchants to the Users.
                    </li>
                    <li>
                      <strong>“Platform”</strong> means any platform owned/subscribed/used by DOR or DOR Group Entities
                      including but not limited to the DOR Website, the DOR App, other mobile applications, devices,
                      URLs/links, notifications, chat bots, DOR’s social media channels or any other communication
                      medium or mechanism used by DOR or DOR Group Entities to provide services to the Users.
                    </li>
                    <li>
                      <strong>“Services”</strong> shall mean goods and/or services offered by or through the Vendor/
                      Merchants on Merchant’s shop, website, e-commerce website, and mobile-based application.
                    </li>
                    <li>
                      <strong>“User OR Client”</strong> shall mean any individual or entity as approved by DOR.
                    </li>
                  </ul>              </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">Agree To Acknowledge Terms of this Agreement:</h2>
                <p className="text-base leading-relaxed text-muted-foreground">
                  By tapping on the tab/button/checkbox of “DOR” or “Request with DOR” or some other button/checkbox of comparable nature, (a) you affirm that qualified under Relevant Law to contract with DOR, (b) you agree to manage transactions, acknowledge the agreements of this Understanding and the Privacy policy as shown on the website and (c) you agree to get communications, notification and data from us through post or other actual medium or electronically (whether through SMS, messages, calls and mechanized calls). Electronic communication will be considered to have been gotten by you when we send the electronic communication to the email address/Mobile number/subtleties given by you during the sign-up process according to our records, or when we post the electronic correspondence on the Site.

                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">User Responsibilities for Platform:

                </h2>
                <p className="text-base leading-relaxed text-muted-foreground">
                  <ul className="list-disc space-y-4 pl-6 text-muted-foreground text-sm">
                    <li>
                      For using the services of DOR, You will have to register and create an account on the Platform by
                      providing details as may be required in the Privacy Policy (“Account”).
                    </li>
                    <li>
                      All registration information you submit is honest, complete, and accurate, and you consent to maintain
                      precise, complete, and up-to-date record information in your account. You are responsible for all activity
                      that occurs under your account.
                    </li>
                    <li>
                      You are responsible for maintaining the confidentiality of your account and fully liable for all activities
                      that occur under your account. You agree to promptly notify DOR of any unauthorized use of your password or
                      account or any other security breach.
                    </li>
                    <li>
                      You agree that you are aware and responsible for all transactions occurring through your Account, including if
                      you knowingly or negligently:
                      <ul className="list-disc pl-6">
                        <li>Allow another person to access your DOR App</li>
                        <li>Permit them to transact for you</li>
                        <li>Transact on behalf of another person, whether by sharing OTPs or in any other way</li>
                      </ul>
                    </li>
                    <li>
                      You are responsible for maintaining the privacy of the Account information and fully accountable for all
                      activities that occur under your Account. You agree to notify DOR immediately of any unauthorized access.
                    </li>
                    <li>
                      You may be held liable to pay damages for losses caused due to unauthorized use of Your Account resulting from
                      your failure to keep your account information secure and confidential.
                    </li>
                    <li>
                      While you are entirely responsible for proving the authenticity of the transaction or exchange of money,
                      DOR may request necessary documents to validate the Lessor and Renter relationship.
                      <br />
                      Example documents: Tenant contract, Rental Agreement, PAN Card, Aadhar Card, etc.
                    </li>
                    <li>
                      You shall not access or use the DOR Application in any way that:
                      <ul className="list-disc pl-6">
                        <li>May be harmful to the operation or content of the DOR Application</li>
                        <li>May be unlawful</li>
                        <li>May be harmful to DOR or other Users</li>
                        <li>May obstruct other Users’ experience on the platform</li>
                        <li>Is intended to defraud Users, DOR, or any Business Partner</li>
                      </ul>
                    </li>
                    <li>
                      You shall not post or transmit any software or files containing viruses, malicious code, or any other
                      harmful components that could damage or disable the DOR Application or any connected network.
                    </li>
                    <li>
                      You shall not delete or alter any content of the DOR Application.
                    </li>
                    <li>
                      Your use of the DOR Application indicates consent to receive automatic updates like bug fixes, patches,
                      enhanced features, and new versions, necessary for effective delivery of DOR Services.
                    </li>
                    <li>
                      Continued use of the DOR Application following such updates implies your acceptance of the same.
                    </li>
                    <li>
                      Not all products, services, and rewards offered on the DOR Application are available in all geographic
                      regions. DOR reserves the right to determine availability and eligibility.
                    </li>
                    <li>
                      You shall request DOR to block the Account and immediately change the password if your device is lost or stolen.
                    </li>
                  </ul>
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">Platform Services for user:</h2>
                <p className="text-base leading-relaxed text-muted-foreground">
                  <ul className="list-disc pl-6">
                    <li>DOR offers a technology platform on www.dorpay.in and at vendor shop, website and mobile based application. DOR’s technology platform empowers users (as Client) for making their Rental payment, Security deposits, Installments on its website and Mobile Application. All valid credit / debit/ cash card/ and other payment instruments are processed using a credit card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between You and the respective issuing bank and payment instrument issuing company. All online bank transfers from valid bank accounts are processed using the gateway provided by the respective issuing bank which supports payment facility to provide these services to You. All such online bank transfers on payment facility are also governed by the terms and conditions agreed to between You and the respective issuing bank. These payments are worked with through an outsider Payment Gateway. By involving this platform for making rental payments, the User affirms that there is a legitimate Lesser and Renter connection between the User and the Recipient and the amount being moved through the platform is addressing the genuine rental worth according to the Understanding We are just giving a platform to work with these rental payments from the User to the Recipient and we are not involved at all in the basic exchanges of money between the User and the Recipient. The User needs to consent to the applicable guidelines if any connected with such Payments/installments and will be liable for any resistance or defaults in such installments. We are not a monetary foundation and proposition no kind of banking or related financial services. We might utilize the services of at least one outsider to offer the types of assistance and interaction your exchanges. We are neither a specialist of the Lesser or the Renter or any closely involved individual in any such settlement. DOR allows You to use Your credit card to make payments to their landlords / apartment complexes / housing societies (in case of Rent Pay), suppliers (in case of business expense payments) and educational institutions (in case of educational fees payment product), collectively referred to hereinafter as Counterparties.</li>
                    <li>DOR offers a technology platform on www.dorpay.in and at vendor shop, website and mobile based application. DOR’s technology platform empowers User to profit a tab presented by outsider vendors at their shops, websites and portable applications (“Vendor”) for Transactions made with or through such Vendor. DOR will get sensible endeavors to work with your Transactions   with a Vendor to get Items, dependent upon the accessibility of Items with the Vendor. DOR just works with the arrangement of a tab and an issue free purchasing experience by the Vendor. For the evasion of any uncertainty, DOR itself doesn’t give Items and DOR isn’t a supplier of Items. It depends on the Dealer to offer Items, which might be mentioned through the Vendor’s shop, site or versatile application. The arrangement of the Items by the Vendor to you and any obligation consequently is accordingly dependent upon the consent (to be) went into among you and the Vendor. DOR isn’t aware of such arrangement. DOR doesn’t anytime of time during any Transactions   among Client and Vendor, take the responsibility for of Items nor does it anytime declare any privileges or claims over the Items presented by Vendor to user.
                    </li>
                  </ul>     <br></br> For empowering the Platform, DOR might cooperate with at least one bank, monetary foundations or different elements (“Financial Partner”). DOR will gather and hold all reports, works, arrangements, checks, drafts, different instruments got from the User including without constraint, post dated checks, request promissory notes, correspondence and records connecting with the installments for the Items, in trust and as specialist for the Vendor, by and large.DOR will keep up with vital records in regard of the Transaction went into by the user with the vendor and amount due in regard of Items and the user consents to sharing of such records by DOR with the Financial Partner or the Vendor to work with the Services. The User concurs that such records as kept up with by DOR will be adequate confirmation of the Transactions went into between the User and Vendors and the sums due thereto, which the Client will not question. DOR maintains whatever authority is needed to change the idea of Administrations occasionally with practically no earlier notification. User recognizes and concurs that DOR might stop (forever or briefly) offering the Types of assistance (or any highlights inside the Services) to you or to clients for the most part at DOR’s only carefulness, without earlier notification to you. You might quit utilizing the Services out of the blue, gave that sums that are expected from you to DOR under the User expressions will be released by you. You don’t have to explicitly illuminate DOR when you quit utilizing the Services. The User recognizes that every Transaction   will be surveyed by DOR as per its own inside principles for handling of such Transactions   and DOR will reserve the privilege to keep the handling from getting any Transactions   at its only carefulness.        </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">Supplemental Terms and conveyance of administrations:</h2>
                <p className="text-base leading-relaxed text-muted-foreground">
                  You concur and recognize that few elements including yet not restricted to DOR Pay,     DOR Money, Rent Payments and Rewards are dependent upon specific supplemental Terms of Purpose set out beneath. Your use of any highlights that have a bunch of Supplemental Terms of Purpose is considered to be acknowledgment of the said Supplemental Terms of Purpose. You further concur that any DOR services might be given to You either straight by DOR or by any DOR Group Substance and specifically, any Payment to you or made by you might be routed through RSOULTEK CONSUTING INDIA PVT. LTD. (“Payment Aggregator”).

                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-2">Platform Fee and Other Charges:

                </h2>
                <p className="text-base leading-relaxed text-muted-foreground">
                  You are liable for any platform fees that might be applicable to specific transactions or utilization of the DOR Application; where you will be informed of such relevant charges, preceding the consummation of any transaction. By agreeing or some other comparable button on the DOR Application, You will be considered to have assented to the charges shown on the said page.

                </p>
                <ul className="list-disc space-y-4 pl-6 text-muted-foreground text-sm">
                  <li>
                    <strong>Returns Policy:</strong>
                    You may request an exchange or return for items bought from DOR, provided the items are sealed/unopened/unused and in their original condition, within the same day of delivery. Please note, return or exchange requests will not be accepted after the day following delivery.
                    <br />
                    DOR is responsible for investigating user complaints and directing users to the vendor/merchants. The ultimate responsibility for replacement or refund lies with the vendor/merchants.
                    <br />
                    DOR is responsible for handling the product within 7 days from delivery. After 7 days, users will be redirected to the vendor, and replacement will be subject to the vendor’s policy.
                    <br />
                    If the issue is unresolved within 7 working days, contact our customer care support at <a href="mailto:support@dorpay.in" className="text-blue-500">support@dorpay.in</a>.
                  </li>

                  <li>
                    <strong>Termination/Cancellation of User:</strong>
                    Upon a request for account deletion or termination by DOR, we will consider consent ended and take appropriate steps.
                    <br />
                    However, DOR may retain transaction records for record-keeping purposes as well as regulatory reasons.
                    <br />
                    Deletion of the account or termination also doesn’t absolve your obligations undertaken before cancellation or termination of the account, including but not limited to the commitment to repay any advance or credit line availed by you.
                    <br />
                    DOR may continue to hold a record of your transactions made on the DOR platform for administrative and historical purposes.
                  </li>

                  <li>
                    <strong>Privacy Policy:</strong>
                    We collect, hold, use, and transfer your personal information in accordance with our <a href="/privacy-policy" className="text-blue-500">Privacy Policy</a>.
                    By agreeing to the Terms of Use, you also consent to our Privacy Policy, which may be updated or changed by us from time to time.
                    <br />
                    You understand and agree that, to the extent permitted by applicable law, any information provided by you regarding DOR may be shared with our subsidiaries, affiliates, or partners, and may be used by us to improve DOR Services. Please refer to the Privacy Policy for further clarity on the subject.
                  </li>

                  <li>
                    <strong>Cookies:</strong>
                    We use cookies to enhance your experience on our website. By using the DOR website, you agree to the use of cookies as per our <a href="/privacy-policy" className="text-blue-500">Privacy Policy</a>.
                    <br />
                    Most websites use cookies to enable us to retrieve user details for each visit. Cookies are used in certain areas of our website to enable the functionality of that area and provide ease of use for visitors.
                  </li>

                  <li>
                    <strong>Use and Protection of Intellectual Property Rights:</strong>
                    The DOR Platform, and its processes, designs, text, videos, graphics, user interfaces, visual interfaces, sounds and music (if any), system code (collectively, the "Content") on the platform, is owned by the organization. The design, structure, selection, coordination, expression, look and feel, and arrangement of such content are protected by copyright, patent, trademark, and other intellectual property laws.
                    <br />
                    The logo, service marks, and trademarks displayed on the platform ("Marks") are the intellectual property of the organization or owned by third parties. You are not permitted to use the Marks without prior consent from the organization or the applicable third party (the owner of the Marks).
                    <br />
                    Access or use of the platform grants no party the right to use trademarks, brand names, logos, or any other marks in any way.
                  </li>

                  <li>
                    <strong>Violation of These Terms:</strong>
                    You agree that any violation by you of these terms will likely harm the organization, for which financial damages would be insufficient, and you agree to the organization obtaining any injunctive or equitable relief deemed necessary in such circumstances.
                    <br />
                    These remedies are in addition to any other remedies the organization may have at law or in equity.
                  </li>

                  <li>
                    <strong>Amendment to Terms of Contract:</strong>
                    DOR reserves the right to add, modify, or amend any or all of these terms at any time without prior notice. You will be bound by such additions, modifications, or amendments once incorporated into these User Terms on DOR's website at <a href="http://www.dorpay.in" className="text-blue-500">www.dorpay.in</a> on the date such changes are made.
                    <br />
                    DOR also reserves the right to transfer or assign its rights and obligations under these User Terms (including but not limited to the transfer of money or assignment of your record with DOR) to any third party without requiring further consent from the user.
                  </li>

                  <li>
                    <strong>Indemnification and Limitation of Liability:</strong>
                    DOR disclaims all liability in regard to the Vendor and their items. You agree to indemnify and keep DOR, its subsidiaries, and licensors indemnified against all expenses, costs, damages, losses, and liabilities caused or endured by DOR or its affiliates related to any user content posted or sent by you during the use of the website or service or any unauthorized use of the website or service in violation of this agreement.
                    <br />
                    Furthermore, you agree to hold the indemnities harmless against any claims made by third parties arising from your use of the platform, any misinformation provided by you, your violation of these Terms and/or the Privacy Policy, or any violation of relevant laws or the rights of another, including intellectual property rights.
                  </li>

                  <li>
                    <strong>Governing Law and Jurisdiction:</strong>
                    These Terms shall be governed by and construed in accordance with the laws of India without regard to conflict of laws principles, and disputes arising in relation thereto shall be subject to the exclusive jurisdiction of courts at Bangalore, India.
                  </li>
                </ul>

              </section>

              <p className="text-sm text-muted-foreground mt-10">
                Last updated: April 14, 2025
              </p>
            </div>
          </main>
          <footer className="bg-background py-12 px-6 md:px-12 border-t border-border">
            <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8">
              <div className="md:col-span-2">
                <img src="/newlogo.png" alt="DORPay Logo" className="w-16 h-16" />

                {/* <h3 className="text-2xl font-semibold mb-4">
                  DORPay<span className="text-primary/80">.</span>
                </h3> */}
                <p className="text-muted-foreground max-w-md mb-6">
                  Discover the perfect property that matches your lifestyle and
                  preferences with our curated selection of premium DORPay.
                </p>
                <div className="flex space-x-4">
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Twitter
                  </a>
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Facebook
                  </a>
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Instagram
                  </a>
                  <a
                    href="#"
                    className="text-muted-foreground hover:text-foreground transition-colors"
                  >
                    LinkedIn
                  </a>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-4">Explore</h4>
                <ul className="space-y-2">
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Properties
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Agents
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Locations
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Blog
                    </a>
                  </li>
                </ul>
              </div>

              <div>
                <h4 className="font-medium mb-4">Contact</h4>
                <ul className="space-y-2 text-muted-foreground">
                  <li>Rsoultek Consulting India Pvt Ltd,</li>
                  <li>
                    CoWrks, RMZ Ecoworld, Ground Floor Bay Area, 6A,
                    Devarabisanahalli,
                  </li>
                  <li>Bengaluru, Karnataka, India- 560103</li>
                  <li>
                    <a
                      href="mailto:support@dorpay.in"
                      className="hover:text-foreground transition-colors"
                    >
                      support@dorpay.in
                    </a>
                  </li>
                  <li>
                    <a
                      href="tel:+919844809969"
                      className="hover:text-foreground transition-colors"
                    >
                      +91 9844809969
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            <div className="max-w-7xl mx-auto mt-12 pt-6 border-t border-border text-center sm:text-left sm:flex sm:justify-between sm:items-center">
              <p className="text-muted-foreground text-sm">
                © {new Date().getFullYear()} DORPay. All rights reserved.
              </p>
              <div className="mt-4 sm:mt-0 flex justify-center sm:justify-end space-x-6 text-sm">
                <a
                  href="/privacy-policy"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  Privacy Policy
                </a>
                <a
                  href="/TermsConditions"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  Terms of Service
                </a>
                <a
                  href="#"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  Cookies Policy
                </a>
              </div>
            </div>
          </footer>
        </div>
      </ThemeProvider>
    </div>
  );
}
